version: 2

# Test pypi to be removed before merging,
registries:
  testpypi:
    type: python-index
    url: https://test.pypi.org/simple/

updates:
  # Separate schedule for 
  - directory: /docs/.sphinx
    package-ecosystem: pip
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    registries:
      - testpypi
    # REMOVE before merging required because using testpypi
    insecure-external-code-execution: allow
